-- Embedded mirror of migrations/0006_llm_chat_capability.sql.
CREATE TABLE provider_connections (id TEXT PRIMARY KEY, display_name TEXT NOT NULL, provider_kind TEXT NOT NULL CHECK(provider_kind IN ('anthropic','gemini')), credential_envelope BLOB NOT NULL, credential_key_version INTEGER NOT NULL CHECK(credential_key_version>0), status TEXT NOT NULL CHECK(status IN ('validating','active','disabled','revoked','validation_failed')), validation_metadata_json TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, revoked_at TEXT);
CREATE TABLE llm_chat_profiles (id TEXT PRIMARY KEY, connection_id TEXT NOT NULL REFERENCES provider_connections(id), model TEXT NOT NULL, max_messages INTEGER NOT NULL CHECK(max_messages BETWEEN 1 AND 128), max_message_bytes INTEGER NOT NULL CHECK(max_message_bytes BETWEEN 1 AND 262144), max_input_bytes INTEGER NOT NULL CHECK(max_input_bytes BETWEEN 1 AND 1048576), max_output_tokens INTEGER NOT NULL CHECK(max_output_tokens BETWEEN 1 AND 16384), timeout_ms INTEGER NOT NULL CHECK(timeout_ms BETWEEN 1000 AND 120000), viewer_requests INTEGER NOT NULL CHECK(viewer_requests BETWEEN 1 AND 10000), app_requests INTEGER NOT NULL CHECK(app_requests BETWEEN 1 AND 100000), rate_window_ms INTEGER NOT NULL CHECK(rate_window_ms BETWEEN 1000 AND 3600000), concurrency_limit INTEGER NOT NULL CHECK(concurrency_limit BETWEEN 1 AND 128), is_default INTEGER NOT NULL DEFAULT 0 CHECK(is_default IN (0,1)), status TEXT NOT NULL CHECK(status IN ('active','disabled','revoked')), revision INTEGER NOT NULL CHECK(revision>0), created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX idx_llm_profiles_default ON llm_chat_profiles(is_default) WHERE is_default=1;
CREATE TABLE llm_host_policy (id INTEGER PRIMARY KEY CHECK(id=1), status TEXT NOT NULL CHECK(status IN ('enabled','disabled')), monthly_token_limit INTEGER CHECK(monthly_token_limit>=1), revision INTEGER NOT NULL CHECK(revision>0), updated_at TEXT NOT NULL);
INSERT INTO llm_host_policy(id,status,monthly_token_limit,revision,updated_at) VALUES(1,'enabled',NULL,1,CURRENT_TIMESTAMP);
CREATE TABLE app_llm_policies (app_id TEXT PRIMARY KEY REFERENCES applications(id), status TEXT NOT NULL CHECK(status IN ('enabled','disabled')), quota_mode TEXT NOT NULL CHECK(quota_mode IN ('inherit','unlimited','specific')), monthly_token_limit INTEGER CHECK(monthly_token_limit>=1), revision INTEGER NOT NULL CHECK(revision>0), updated_by TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, CHECK((quota_mode='specific' AND monthly_token_limit IS NOT NULL) OR (quota_mode!='specific' AND monthly_token_limit IS NULL)));
CREATE TABLE llm_usage (app_id TEXT NOT NULL REFERENCES applications(id), period_start TEXT NOT NULL, used_tokens INTEGER NOT NULL CHECK(used_tokens>=0), reserved_tokens INTEGER NOT NULL CHECK(reserved_tokens>=0), in_flight INTEGER NOT NULL CHECK(in_flight>=0), updated_at TEXT NOT NULL, PRIMARY KEY(app_id,period_start));
CREATE TABLE llm_reservations (id TEXT PRIMARY KEY, app_id TEXT NOT NULL REFERENCES applications(id), profile_id TEXT NOT NULL REFERENCES llm_chat_profiles(id), identity_id TEXT NOT NULL REFERENCES identities(id), period_start TEXT NOT NULL, reserved_tokens INTEGER NOT NULL CHECK(reserved_tokens>0), status TEXT NOT NULL CHECK(status IN ('calling','succeeded','failed','cancelled','ambiguous')), created_at TEXT NOT NULL, finished_at TEXT);
CREATE INDEX idx_llm_reservations_app_period ON llm_reservations(app_id,profile_id,period_start,status);
