// @ts-check
import { tiny } from "@tinyhost/sdk";
import { describeTinyError } from "../../shared/errors.js";
import { beginTurn, completeTurn } from "./history.js";
const thread=/** @type {HTMLElement} */(document.querySelector("#thread")),form=/** @type {HTMLFormElement} */(document.querySelector("#form")),prompt=/** @type {HTMLTextAreaElement} */(document.querySelector("#prompt")),send=/** @type {HTMLButtonElement} */(document.querySelector("#send")),cancel=/** @type {HTMLButtonElement} */(document.querySelector("#cancel")),notice=/** @type {HTMLElement} */(document.querySelector("#notice")),status=/** @type {HTMLElement} */(document.querySelector("#status")),empty=/** @type {HTMLElement} */(document.querySelector("#empty"));
/** @type {{role:"user"|"assistant",content:string}[]} */ let history=[];let controller;
function setBusy(busy){send.disabled=busy;cancel.disabled=!busy;prompt.disabled=busy;if(busy)status.textContent="Thinking…";if(!busy)prompt.focus()}
function add(role,text,pending=false){empty.hidden=true;const item=document.createElement("article");item.className="list-item";item.dataset.pending=String(pending);const label=document.createElement("strong"),content=document.createElement("span");label.textContent=role;content.textContent=text;item.append(label,content);thread.append(item);thread.scrollTop=thread.scrollHeight;return item}
function show(e){const d=describeTinyError(e);notice.textContent=`${d.title}: ${d.message}`;notice.hidden=false;status.textContent="Could not send"}
form.addEventListener("submit",async e=>{e.preventDefault();const text=prompt.value.trim();if(!text||controller)return;notice.hidden=true;controller=new AbortController();setBusy(true);const before=history;history=beginTurn(history,text);add("You",text);prompt.value="";const pending=add("Assistant","Thinking…",true);try{const reply=await tiny.llm.chat.complete({messages:history},{signal:controller.signal});history=completeTurn(history,reply.message.content);pending.dataset.pending="false";pending.querySelector("span").textContent=reply.message.content;status.textContent="Ready"}catch(e){history=before;pending.remove();if(e instanceof DOMException&&e.name==="AbortError"){status.textContent="Cancelled"}else show(e)}finally{controller=undefined;setBusy(false)}});cancel.onclick=()=>controller?.abort();
